### ISSUE TITLE
Custom Metadata not updated

### ISSUE THREAD

**Issue by JedCarrNV** [s-KaiNet/spsave#20]
Hi there,

Trying to update some custom metadata with a glob. Here are my options:

``` JavaScript
saveOptions = {
    glob: 'xml/pet 123122.xml',
    notification: true,
    folder: '/Pet%2097%20Archive',
    filesMetaData: [{
        metadata: {
            '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},
            'Pet Name': 'Doggy McDogFace',
            'Pet ID#': '666',
            'Title':'McDogFace is awesome'
        }
    }]
}
```

The file uploads just fine, but Pet Name, ID and title don't get updated.  Not sure I'm doing something wrong.  Any help will be greatly appreciated.

**Comment by s-KaiNet** [comment]
Take a look at [this](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#save-file-using-its-name-and-content-update-metadata-for-the-file) recipe - you need to provide file name option:

``` javascript
[{
    fileName: 'pet 123122.xml',
    metadata: {
        '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},
        'Pet Name': 'Doggy McDogFace',
        'Pet ID#': '666',
        'Title':'McDogFace is awesome'
    }
}]
```

`fileName` required, because when using globs like `xml/*.*`, `spsave` needs to know how to map each file to metadata.  
For multiple files you will write: 

``` javascript
glob: 'xml/*.xml',
    notification: true,
    folder: '/Pet%2097%20Archive',
    filesMetaData: [{
        fileName: 'pet 1.xml',
        metadata: {
            '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},
            'Pet Name': 'Doggy McDogFace',
            'Pet ID#': '666',
            'Title':'McDogFace is awesome'
        }
    }, 
    {
        fileName: 'pet 2.xml',
        metadata: {
            '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},
            'Pet Name': 'Cool dog',
            'Pet ID#': '777',
            'Title':'McDogFace is awesome'
        }
    }]
```

**Comment by JedCarrNV** [comment]
Ah that was it.

Also the Field names needed be escaped as Pet_x0020_Name and Pet_x0020_ID_x0023_ 

Thank you, you are doing awesome work!

**Comment by s-KaiNet** [comment]
Right, actually internal names should be used as field names.

**Comment by SteenMolberg** [comment]
Thx harry,

That was just what I needed!!

/Steen

Fra: Sergei Sergeev [mailto:notifications@github.com]
Sendt: 8. september 2016 20:35
Til: s-KaiNet/spsave spsave@noreply.github.com
Emne: Re: [s-KaiNet/spsave] Custom Metadata not updated (#20)

Take a look at thishttps://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#save-file-using-its-name-and-content-update-metadata-for-the-file recipe - you need to provide file name option:

[{

```
fileName: 'pet 123122.xml',

metadata: {

    '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},

    'Pet Name': 'Doggy McDogFace',

    'Pet ID#': '666',

    'Title':'McDogFace is awesome'

}
```

}]

fileName required, because when using globs like xml/_._, spsave needs to know how to map each file to metadata.

For multiple files you will write:

glob: 'xml/*.xml',

```
notification: true,

folder: '/Pet%2097%20Archive',

filesMetaData: [{

    fileName: 'pet 1.xml',

    metadata: {

        '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},

        'Pet Name': 'Doggy McDogFace',

        'Pet ID#': '666',

        'Title':'McDogFace is awesome'

    }

},

{

    fileName: 'pet 2.xml',

    metadata: {

        '__metadata':{type:'SP.Data.Pet_x0020_97_x0020_ArchiveItem'},

        'Pet Name': 'Cool dog',

        'Pet ID#': '777',

        'Title':'McDogFace is awesome'

    }

}]
```
