### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY on bulk Upload Docs to SharePoint 2013 On-premises with ADFS

### ISSUE THREAD

**Issue by joaojmendes** [s-KaiNet/spsave#26]
Hi,

After upload about 100 documents with spsave to Doclib I have the error "UNABLE_TO_GET_ISSUER_CERT_LOCALLY " , 
our SharePoint has ADFS Authentication.

Can help to found the reason for this error?

Thank's

**Comment by s-KaiNet** [comment]
I'm not sure if this issue connected with `spsave`. Try to google for the error `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` - you will find a lot of issues around nodejs.   
Some of the info I found    

> The error itself just means that a TLS certificate in the chain is signed by an unknown CA, presumably the cert your proxy uses.  

Since the most probably that's certificated issue, try to add your ADFS certificates to trusted root authority local machine.    
You can also try to set `npm config set strict-ssl false` - insecure option, but might work.   
Please try this first or other suggestions by google, if it doesn't help, please comment that the issue still exist

**Comment by s-KaiNet** [comment]
Closing for now.. feel free to reopen
