### ISSUE TITLE
Works on Windows but 401 on OSX

### ISSUE THREAD

**Issue by Djemel** [s-KaiNet/spsave#29]
Hello,

I am trying to get spsave to work on OSX for an on-premise & NTLM authentication.

It works fine with Windows but I am getting a "401 - undefined" running the same Node.js code on a MacBook Pro.

Is there something I need to configure on OSX to get NTLM auth to work.
It seems spsace create a "Authentication" header with "NTLM ......" but fails on the POST to get /_api/contextinfo

**Comment by s-KaiNet** [comment]
Hi,   
I haven't tested this module on OSX, however I haven't received such kind of issue as well. That's why I'm thinking it works on OSX, but I'm not sure what is the cause of your issue.    
Right now I don't environment to test it on OSX, can you please try other auth methods?   
Can you please also post full stack trace from console?
Are you able to login in OSX using same NTLM credentials into SharePoint?

**Comment by koltyakov** [comment]
I was managed to test it on macOS Sierra (Version 10.12.6) with NTLM and SharePoint 2016. It works just fine. So I guess that an issue in something else.

Node: v7.4.0 and v8.5.0.

@Djemel, can you share your spsave auth config (with pass/login replaced of course)?

**Comment by Djemel** [comment]
Sorry - I do not understand what happened but this morning after a reboot of my machine everything works fine.
May be something linked to "Enterprise Connect" we are using here.
Thank you for the quick feedback and tests.
