### ISSUE TITLE
Invalid characters from CRA js file

### ISSUE THREAD

**Issue by rylew2** [s-KaiNet/spsave#47]
I'm attempting to use spsave to save files from CRA build to SharePoint.

```
The file or folder name \\\"MyProject/static/js/runtime~main.d653cc00.js\\\" contains invalid characters. Please use a different name. Common invalid characters include the following # % & * : < > ? / { | }
```

I'm assuming it's the tilde - but I believe that's what create-react-app is using these days. 
I guess the file is used to load and run the app - https://facebook.github.io/create-react-app/docs/production-build

**Comment by koltyakov** [comment]
Hi @rylew2,

Looks like something wrong with your initiation object. `~` should not be banned in SharePoint.

![image](https://user-images.githubusercontent.com/7816483/57976034-966e7500-79df-11e9-992b-e457fa96abf8.png)

![image](https://user-images.githubusercontent.com/7816483/57976039-ac7c3580-79df-11e9-8727-f796fec462a0.png)

**Comment by rylew2** [comment]
If I try to drag and drop the same file to a custom folder in SharePoint Designer it fails with the same invalid character message. This is SP2013 and spsave ^3.1.5

**Comment by koltyakov** [comment]
I tested in SPO and 2016. While it's banned in 2013, the only way is reconfiguring your CRA build or/and deploy pipeline to do not generate ~ in filenames.

**Comment by rylew2** [comment]
Ok thanks - I'll ask on SO: https://stackoverflow.com/questions/56203855/create-react-app-build-files-tilde-character

Hopefully there's a way to change config. Worst case I will revert to a previous version of CRA which doesn't use tilde. It only broke when I upgraded CRA.

**Comment by s-KaiNet** [comment]
Hi Ryan,   
here is the solution for you (works for me with the latest CRA):   
1. Scaffold a project with the latest CRA
2. Install `npm install @rescripts/cli --save-dev`
3. In the root directory of your project create a file `.rescriptsrc.js` and put below code inside:  
```
module.exports = config => {
    config.optimization.splitChunks.automaticNameDelimiter = '_';
    if (config.optimization.runtimeChunk) {
        config.optimization.runtimeChunk = {
            name: entrypoint => `runtime_${entrypoint.name}`
        };
    }
    return config;
};
```
4. In `package.json` in sripts section add a new entry `"build-re": "rescripts build"`  
5. Now when running `npm run build-re` it will generate `_` instead of `~` in file names.   

More on `rescripts` [here](https://github.com/harrysolovay/rescripts).

**Comment by rylew2** [comment]
Works like a charm - thank you @s-KaiNet !
