### ISSUE TITLE
Create an empty folder

### ISSUE THREAD

**Issue by cristoni** [s-KaiNet/spsave#64]
Hello,
i'm using this library to upload some files to a sharepoint online, and it works great.
Now i'm trying to create new empty folders to populate them later on, is this possible with spsave?

**Comment by s-KaiNet** [comment]
Hi, 

`spsave` doesn't support empty folders creation. However, you can use [sp-request](https://github.com/s-KaiNet/sp-request) module in order to send REST requests to SharePoint to create desired folders. 

The sample code to create a folder with REST API (from [here](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)):

```
POST https://{site_url}/_api/web/folders
Authorization: "Bearer " + accessToken
Accept: "application/json;odata=verbose"
Content-Type: "application/json"
Content-Length: {length of request body as integer}
X-RequestDigest: "{form_digest_value}"

{
  "__metadata": {
    "type": "SP.Folder"
  },
  "ServerRelativeUrl": "/document library relative url/folder name"
}
```  

`sp-request` uses the same auth mechanism, so you can just reuse what you have for `spsave`;

**Comment by s-KaiNet** [comment]
You can also check out [this code](https://github.com/s-KaiNet/spsave/blob/823b049add64502891d82070d8f442ce4cd2bec3/src/utils/FoldersCreator.ts#L69) which creates folders with `sp-request` (used internally by `spsave`)

**Comment by cristoni** [comment]
Thank you very much for the fast response, i'll try it and let you know if i managed to make it work 😄

**Comment by cristoni** [comment]
Goodmorning,
i've tried the solution you proposed and achieved exactly what i needed, thank you.
