### ISSUE TITLE
Default credentials

### ISSUE THREAD

**Issue by ViktorHofer** [s-KaiNet/spsave#9]
Hello,

thanks for that great module. I'm using it for multiple projects. Currently I always have to specify a username and password when using it in combination with gulp-spsave. Is it possible, if no credentials supplied, use the default one in the http requests?

Thanks,
Viktor

**Comment by s-KaiNet** [comment]
Hi Victor, thank you.  
I thought about this in the past but didn't find the right answer. The problem is that I'm using http ntlm handshake and protocol requires username and password to be present. From my experience it's not possible to extract windows user password.  
May be another option is to use something different for http windows authentication, but I don't know about such tools.   

If you have an idea how to do that, please tell me :)
